"""The ``update-offsets`` orchestration — attach, scan, build, write (docs/02 §4).

Ties the pure pieces together. The split mirrors the rest of the reader:

* :func:`discover` and :func:`persist` are **pure/offline** — given two snapshots (or a built table
  + report), they derive, assemble, and write files. The offline suite drives these against a
  synthetic planted layout, proving the tool's output is consumable by the C4a decoder.
* :func:`run_update_offsets` is the **live orchestration** — it attaches read-only to Tekken 8,
  detects the version, reads the two Jin-vs-Kazuya snapshots (prompting the user to act between
  them), and calls the pure pieces. It needs the running game, so it is ``# pragma: no cover``;
  every step beneath the attach is covered via :func:`discover`/:func:`persist`.

Read-only throughout: it reads process memory through the :class:`MemorySource` seam and writes a
*file* — never the game (docs/02 §2).
"""

from __future__ import annotations

import json
import math
import time
from collections.abc import Callable, Iterator, Sequence
from datetime import UTC, datetime
from pathlib import Path

from tekken_coach.reader.discovery.basescan import (
    GlobalLocated,
    Located,
    Progress,
    derive_base_layout,
)
from tekken_coach.reader.discovery.builder import (
    build_offset_table,
    register_version,
    write_offset_table,
)
from tekken_coach.reader.discovery.derive import DiscoverySnapshots, derive_layout
from tekken_coach.reader.discovery.heapscan import DeriveInputs, derive_layout_scan
from tekken_coach.reader.discovery.holderscan import HolderMatch, derive_holder_layout
from tekken_coach.reader.discovery.manifest import (
    DEFAULT_MANIFEST_PATH,
    ProbeManifest,
    load_probe_manifest,
    state_map_path,
)
from tekken_coach.reader.discovery.report import DiagnosticReport, build_report
from tekken_coach.reader.discovery.scanners import Region, snapshot_region
from tekken_coach.reader.faults import MemoryReadError, OffsetTableError
from tekken_coach.reader.memory_source import MemorySource
from tekken_coach.reader.offsets import (
    DEFAULT_OFFSETS_DIR,
    EncodedStateSpec,
    OffsetTable,
    load_offset_index,
    load_state_map,
)

_DEFAULT_NOTES = (
    "Generated by update-offsets (C4c) — clean-room Jin-vs-Kazuya re-discovery. Derived fields are "
    "confident (doctor-validated); other fields carried from the seed table and need calibration."
)

_DERIVE_NOTES = (
    "Generated by update-offsets --derive (C4h) — clean-room, FULLY DERIVED layout. Locates the "
    "entity struct on the heap by behavior (Kazuya's id 12 beside a plausible id at a "
    "similar-struct stride whose acting player's move_id changed across the action window), then "
    "reverse-scans the static data for a pointer path that survives a REALLOCATION. Derived: the "
    "player anchor + pointer path (no seeded chain), stride, char_id (offset AND Jin's id), "
    "move_id, damage_taken (computed health), position (transform component), and the global/match "
    "anchor + frame_counter/round. Seeded best-effort (translated onto the derived base, flagged "
    "for re-derivation): the encoded state-word OFFSETS (docs/02 §8), match_phase/game_mode, "
    "heat/rage/input/facing, the state_codes maps."
)

_HOLDER_SCAN_NOTES = (
    "Generated by update-offsets --holder-scan (C4i) — clean-room adoption of the live T8 holder "
    "model (Irony/opendojo/ParadiseAigo, facts/data). Derived: the holder anchor (an AoB CODE "
    "signature in .text -> a RIP-relative .data slot -> the holder object), TWO per-player pointer "
    "slots (holder+0x30 / +0x38 to SEPARATE allocations, not a stride), char_id, move_id, "
    "damage_taken (computed health — HP is encrypted on T8), and the global/match anchor + "
    "frame_counter/round, all confirmed by the BEHAVIORAL oracle (the acting player's move_id "
    "changed across the action window). Position is the transform component. Seeded: the encoded "
    "state-word offsets (their VALUE semantics need the docs/02 §8 observation calibration), "
    "match_phase + game_mode (capture refuses to record until calibrated), heat/rage/input/facing, "
    "the state_codes maps. The AoB is the durable self-healing anchor; a patch that moves the "
    "storing function is a re-source of the pattern, not a re-seed of offsets."
)

_BASE_SCAN_NOTES = (
    "Generated by update-offsets --base-scan (C4d/C4e/C4f/C4g) — clean-room code-signature "
    "derivation. Derived: player anchor (module base_offset + pointer chain + AOB signature) "
    "confirmed by a BEHAVIORAL oracle (the acting player's move_id changed from its round-start "
    "value in at least one sample of the action window), stride, char_id, move_id, health, "
    "position (transform component), and the global/match anchor + frame_counter/round by the same "
    "temporal "
    "argument, with the frame delta banded to the window's measured duration. Seeded: the encoded "
    "state-word offsets (their VALUE semantics need the docs/02 §8 observation calibration), "
    "match_phase + game_mode (until those are calibrated, capture refuses to record), "
    "heat/rage/input/facing, the state_codes maps."
)


# The single action both behavioral oracles read, and the only thing the user has to get right.
# It is one prompt doing triple duty (docs/02 §4): the walk moves `pos_x` (locating the transform
# component), the jab and the jump each change `move_id` (confirming the struct really is the one
# the player controls), and a *connected* jab raises P2's `damage_taken` (corroboration, not a
# requirement — the jab may whiff).
#
# C4f asked the user to press Enter mid-jump, because it compared `move_id` at exactly two instants.
# That is not a thing a person can do: the jump animation is over long before an alt-tab completes,
# `move_id` is back at its idle value, and the real struct is rejected as frozen (confirmed live —
# the scan found zero behaving candidates). C4g times a window instead and accepts a `move_id` that
# changed in ANY sample, so the user has nothing to time at all: alt-tab, then move.
ACT_PROMPT = (
    "Round start captured.\n"
    "\n"
    "Press Enter, then ALT-TAB BACK TO THE GAME. After a {lead_in:.0f}s countdown the scan\n"
    "watches for ~{window:.0f}s. For all of that time, as P1 (Jin), keep acting — on repeat:\n"
    "  walk forward   -> moves pos_x, locating the transform component\n"
    "  jab P2         -> changes move_id (and raises P2's damage_taken if it connects)\n"
    "  jump           -> changes move_id again, whether or not the jab connected\n"
    "\n"
    "Nothing has to be timed. The scan samples continuously and accepts a struct whose move_id\n"
    "changed in ANY sample, so you only have to be moving while it watches."
)


def _act_prompt(manifest: ProbeManifest) -> str:
    """The action prompt, with the manifest's window durations filled in (they are data)."""
    return ACT_PROMPT.format(
        lead_in=manifest.action_lead_in_seconds, window=manifest.action_window_seconds
    )


# The older C4c value-scan path takes a single before/after pair with no window, so it keeps a
# blocking prompt: it only needs `pos_x` to differ and the frame counter to have advanced, neither
# of which is transient.
WALK_PROMPT = "Round start captured. Now walk P1 (Jin) forward a step, then press Enter."


def _now_iso() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def discover(
    snap: DiscoverySnapshots,
    *,
    module: str,
    module_base: int,
    game_version: str,
    manifest: ProbeManifest,
    seed: OffsetTable,
    seed_version: str,
    discovered_at: str | None = None,
    notes: str = _DEFAULT_NOTES,
) -> tuple[OffsetTable | None, DiagnosticReport]:
    """Derive a layout from two snapshots and assemble a candidate table + diagnostic report (pure).

    Returns ``(table, report)``; ``table`` is ``None`` when the confident core (both anchors + a
    stride) did not resolve — the report then explains what is unresolved so the user can widen the
    manifest and re-run, rather than a broken table being written.
    """
    result = derive_layout(snap, module=module, module_base=module_base, manifest=manifest)
    report = build_report(
        result,
        game_version=game_version,
        module_base=module_base,
        seed=seed,
        seed_version=seed_version,
    )
    table: OffsetTable | None = None
    core_resolved = (
        result.player_anchor is not None
        and result.global_anchor is not None
        and result.stride is not None
    )
    if core_resolved:
        table = build_offset_table(
            result,
            seed,
            game_version=game_version,
            discovered_at=discovered_at or _now_iso(),
            notes=notes,
        )
    return table, report


def discover_base(
    source: MemorySource,
    *,
    module: str,
    module_base: int,
    game_version: str,
    manifest: ProbeManifest,
    seed: OffsetTable,
    seed_version: str,
    source_after: MemorySource | None = None,
    during: Sequence[MemorySource] | None = None,
    located: Located | None = None,
    global_located: GlobalLocated | None = None,
    sweep_global: bool = True,
    sweep_player: bool = True,
    state_map: EncodedStateSpec | None = None,
    progress: Progress | None = None,
    discovered_at: str | None = None,
    notes: str = _BASE_SCAN_NOTES,
) -> tuple[OffsetTable | None, DiagnosticReport]:
    """C4d/C4e: derive both anchors via the code-signature scans, assemble a candidate table (pure).

    Mirrors :func:`discover` but for the code-signature path: it reads through the ``MemorySource``
    seam (following pointer chains), so it takes ``source``(s) rather than pre-captured windows.
    ``source_after`` (a snapshot at the end of the user's action) enables the position derivation
    and the behavioral confirmation of both anchors; without it the player landing is accepted on a
    single instant and flagged as unconfirmed. ``during`` is the whole action window the behavioral
    oracle folds over — a candidate's ``move_id`` only has to differ in *one* of those samples,
    which is what makes the oracle satisfiable by a person (C4g); it defaults to the single-sample
    ``[source_after]``. ``located`` / ``global_located`` reuse sweeps the caller already ran, and
    ``sweep_player`` / ``sweep_global`` say whether a missing one means "found nothing" (the live
    path, which must sweep before the user acts) or "not swept yet". ``progress`` logs the sweeps.
    ``state_map`` is the encoded-state value -> meaning data written into the table. Returns
    ``(table, report)``; ``table`` is ``None`` when the player anchor or a constant stride did not
    resolve (e.g. the two-level P2 case) — the report then explains what to do.
    """
    result = derive_base_layout(
        source,
        module=module,
        module_base=module_base,
        manifest=manifest,
        seed=seed,
        source_after=source_after,
        during=during,
        located=located,
        global_located=global_located,
        sweep_global=sweep_global,
        sweep_player=sweep_player,
        state_map=state_map,
        progress=progress,
    )
    report = build_report(
        result,
        game_version=game_version,
        module_base=module_base,
        seed=seed,
        seed_version=seed_version,
    )
    table: OffsetTable | None = None
    core_resolved = (
        result.player_anchor is not None
        and result.global_anchor is not None
        and result.stride is not None
    )
    if core_resolved:
        table = build_offset_table(
            result,
            seed,
            game_version=game_version,
            discovered_at=discovered_at or _now_iso(),
            notes=notes,
        )
    return table, report


def discover_derive(
    inputs: DeriveInputs,
    *,
    module: str,
    module_base: int,
    game_version: str,
    manifest: ProbeManifest,
    seed: OffsetTable,
    seed_version: str,
    state_map: EncodedStateSpec | None = None,
    discovered_at: str | None = None,
    notes: str = _DERIVE_NOTES,
) -> tuple[OffsetTable | None, DiagnosticReport]:
    """C4h: derive the whole layout from behavior (no seeded offsets), assemble a table (pure).

    Mirrors :func:`discover_base` but drives the fully-derived scan
    (:func:`~tekken_coach.reader.discovery.heapscan.derive_layout_scan`): it locates the entity
    struct on the enumerated heap by behavior, reverse-scans for a reallocation-surviving static
    path, and derives every field offset + the stride + Jin's id as outputs. ``inputs`` bundles the
    round-start / action-window / post-action / reallocation captures. Returns ``(table, report)``;
    ``table`` is ``None`` when the confident core (both anchors + a stride) did not resolve.
    """
    result = derive_layout_scan(
        inputs,
        module=module,
        module_base=module_base,
        manifest=manifest,
        seed=seed,
        state_map=state_map,
    )
    report = build_report(
        result,
        game_version=game_version,
        module_base=module_base,
        seed=seed,
        seed_version=seed_version,
    )
    table: OffsetTable | None = None
    core_resolved = (
        result.player_anchor is not None
        and result.global_anchor is not None
        and result.stride is not None
    )
    if core_resolved:
        table = build_offset_table(
            result,
            seed,
            game_version=game_version,
            discovered_at=discovered_at or _now_iso(),
            notes=notes,
        )
    return table, report


def discover_holder(
    source: MemorySource,
    *,
    module: str,
    module_base: int,
    game_version: str,
    manifest: ProbeManifest,
    seed: OffsetTable,
    seed_version: str,
    source_after: MemorySource | None = None,
    during: Sequence[MemorySource] | None = None,
    holder: HolderMatch | None = None,
    slot_rva: int | None = None,
    global_located: GlobalLocated | None = None,
    sweep_global: bool = True,
    state_map: EncodedStateSpec | None = None,
    progress: Progress | None = None,
    discovered_at: str | None = None,
    notes: str = _HOLDER_SCAN_NOTES,
) -> tuple[OffsetTable | None, DiagnosticReport]:
    """C4i: adopt the holder model — AoB code-sig -> holder -> two per-player slots (pure).

    Mirrors :func:`discover_base` but drives the holder derivation
    (:func:`~tekken_coach.reader.discovery.holderscan.derive_holder_layout`): it finds the holder's
    ``.data`` slot by a RIP-relative AoB code signature, resolves the two per-player pointers, and
    confirms behaviorally. ``holder`` / ``slot_rva`` reuse a pre-prompt find (the live path must
    locate before the user acts, then confirm across the window). Returns ``(table, report)``;
    ``table`` is ``None`` when the holder or the confident core did not resolve.
    """
    result = derive_holder_layout(
        source,
        module=module,
        module_base=module_base,
        manifest=manifest,
        seed=seed,
        source_after=source_after,
        during=during,
        holder=holder,
        slot_rva=slot_rva,
        global_located=global_located,
        sweep_global=sweep_global,
        state_map=state_map,
    )
    report = build_report(
        result,
        game_version=game_version,
        module_base=module_base,
        seed=seed,
        seed_version=seed_version,
    )
    table: OffsetTable | None = None
    core_resolved = (
        result.player_anchor is not None
        and result.global_anchor is not None
        and result.has_player_addressing
    )
    if core_resolved:
        table = build_offset_table(
            result,
            seed,
            game_version=game_version,
            discovered_at=discovered_at or _now_iso(),
            notes=notes,
        )
    return table, report


def persist(
    table: OffsetTable, report: DiagnosticReport, *, offsets_dir: str | Path = DEFAULT_OFFSETS_DIR
) -> DiagnosticReport:
    """Write ``table`` to ``<offsets_dir>/<version>.json`` and register it; annotate the report.

    Fail-closed behavior elsewhere is untouched: this only *adds* a version binding (additive), so
    an unknown *other* version still fails closed at select time (docs/02 §3).
    """
    path = write_offset_table(offsets_dir, table)
    register_version(offsets_dir, table.game_version, file_name=path.name)
    report.table_written = str(path)
    report.index_written = str(Path(offsets_dir) / "index.json")
    return report


def _load_seed(offsets_dir: str | Path) -> tuple[OffsetTable, str]:
    """Load the seed table (the index's detected/known-good build) for carrying non-derived fields.

    Raises :class:`OffsetTableError` if no baseline exists — update-offsets refines a prior table
    rather than inventing one from nothing; bring-up ships the C4a placeholder as that baseline.
    """
    from tekken_coach.reader.offsets import select_offset_table  # noqa: PLC0415

    index = load_offset_index(offsets_dir)
    seed_version = index.detected_version
    try:
        seed = select_offset_table(seed_version, offsets_dir)
    except OffsetTableError as exc:
        raise OffsetTableError(
            f"no seed offset table for the index's detected_version {seed_version!r}; "
            "update-offsets carries non-derived fields from a prior table — keep the checked-in "
            "baseline (the C4a placeholder) in place. Original error: " + str(exc)
        ) from exc
    return seed, seed_version


def run_update_offsets(
    process_name: str,
    *,
    offsets_dir: str | Path = DEFAULT_OFFSETS_DIR,
    manifest_path: str | Path = DEFAULT_MANIFEST_PATH,
    version_override: str | None = None,
    act_prompt: Callable[[str], None] | None = None,
) -> tuple[OffsetTable | None, DiagnosticReport]:  # pragma: no cover - attaches to a live game
    """Full live re-discovery: attach read-only, scan the Jin-vs-Kazuya setup, write the table.

    Steps: attach (read-only) -> detect version -> read snapshot A at round start -> prompt the user
    to walk P1 and press a button -> read snapshot B -> derive -> build + write the candidate table
    and register the version -> return ``(table, report)``. Windows-only, user-run. Everything below
    the attach/read is offline-tested via :func:`discover`/:func:`persist`.
    """
    from tekken_coach.reader.version import detect_running_version  # noqa: PLC0415
    from tekken_coach.reader.win_source import WinMemorySource  # noqa: PLC0415

    prompt = act_prompt if act_prompt is not None else _default_act_prompt
    manifest = load_probe_manifest(manifest_path)
    seed, seed_version = _load_seed(offsets_dir)

    source: MemorySource = WinMemorySource(process_name)
    version = version_override or detect_running_version(process_name)
    module_base = source.module_base(manifest.module)

    snap_before = _read_snapshots(source, manifest)
    prompt(WALK_PROMPT)
    snap_after = _read_snapshots(source, manifest)
    snap = DiscoverySnapshots(
        player_before=snap_before[0],
        player_after=snap_after[0],
        global_before=snap_before[1],
        global_after=snap_after[1],
    )

    table, report = discover(
        snap,
        module=manifest.module,
        module_base=module_base,
        game_version=version,
        manifest=manifest,
        seed=seed,
        seed_version=seed_version,
    )
    if table is not None:
        persist(table, report, offsets_dir=offsets_dir)
    return table, report


def run_update_offsets_base(
    process_name: str,
    *,
    offsets_dir: str | Path = DEFAULT_OFFSETS_DIR,
    manifest_path: str | Path = DEFAULT_MANIFEST_PATH,
    version_override: str | None = None,
    act_prompt: Callable[[str], None] | None = None,
    progress: Progress | None = None,
) -> tuple[OffsetTable | None, DiagnosticReport]:  # pragma: no cover - attaches to a live game
    """C4d/C4e/C4g live re-discovery: attach read-only, code-sig-scan both structs, write the table.

    Steps: attach (read-only) -> detect version -> code-signature sweep for the player-struct and
    global-struct *candidates* at round start -> prompt the user to act (:data:`ACT_PROMPT`) -> let
    them alt-tab back -> **sample a timed action window**, folding each candidate's ``move_id`` over
    every sample -> confirm the global struct against the window's measured duration -> run the
    position scan -> derive -> build + write the candidate table + register the version.
    Windows-only, user-run. The scans follow pointer chains through the live ``MemorySource``;
    everything below the attach is offline-tested via :func:`discover_base` against a planted flat
    image, and the window itself via a planted *series* of images.

    Both sweeps run **once, here**, before the prompt, and their results are confirmed after it —
    not as an optimization but because **both oracles are behavioral**. The global oracle needs the
    frame counter at two instants a known duration apart; the player oracle needs the acting
    player's ``move_id`` across a window, because a struct that merely reads plausibly at round
    start is not necessarily the one the player is controlling (it was not, live, on 5.02.01) *and*
    because ``move_id`` is transient — a jab lasts half a second, so the moment the user's finger
    reaches Enter it has already gone back to idle (C4g). A live handle only ever reads *now*, so
    sampling across the user's action is the only way to observe either signal. ``progress`` (from
    the command layer) makes the sweeps and the window observable.
    """
    from tekken_coach.reader.discovery.basescan import (  # noqa: PLC0415
        LayeredMemorySource,
        confirm_global,
        confirm_players,
        frame_delta_band,
        global_candidates,
        player_candidates,
        rebase_global_candidates,
    )
    from tekken_coach.reader.discovery.pe import parse_module_image  # noqa: PLC0415
    from tekken_coach.reader.version import detect_running_version  # noqa: PLC0415
    from tekken_coach.reader.win_source import WinMemorySource  # noqa: PLC0415

    prompt = act_prompt if act_prompt is not None else _default_act_prompt
    manifest = load_probe_manifest(manifest_path)
    seed, seed_version = _load_seed(offsets_dir)
    state_map = load_state_map(state_map_path(manifest, manifest_path))

    live: MemorySource = WinMemorySource(process_name)
    version = version_override or detect_running_version(process_name)
    module_base = live.module_base(manifest.module)
    # Parsed once and handed to both sweeps (they bound themselves to the same data sections). Each
    # sweep only announces a PE parse it performed itself, so announce this one here.
    image = parse_module_image(lambda rva, n: live.read(module_base + rva, n))
    if progress is not None:
        progress(
            f"  parsed PE: SizeOfImage {image.size_of_image // 1024} KiB, "
            f"{len(image.sections)} sections"
        )

    # Instant A. Both sweeps produce *candidates*, not answers.
    players = player_candidates(
        live,
        module=manifest.module,
        module_base=module_base,
        manifest=manifest,
        image=image,
        progress=progress,
    )
    globals_ = []
    if manifest.global_scan is not None:
        globals_ = global_candidates(
            live,
            module=manifest.module,
            module_base=module_base,
            image=image,
            spec=manifest.global_scan,
            progress=progress,
        )

    # Freeze every candidate struct at round start so the position scan has a genuine *before*
    # snapshot whichever candidate the action confirms: a single live handle only reads the current
    # instant. The static chain re-resolves either way — that is exactly why C4d anchors in code.
    frozen: dict[int, Region] = {}
    if players is not None and manifest.base_scan is not None:
        span = manifest.base_scan.struct_span
        for match in players.strong:
            if match.p1_base in frozen:
                continue
            try:
                frozen[match.p1_base] = Region(
                    base=match.p1_base, data=live.read(match.p1_base, span)
                )
            except MemoryReadError:
                continue

    prompt(_act_prompt(manifest))
    _countdown(manifest.action_lead_in_seconds, progress)

    # The window opens. Re-read the global candidates' round-start values *now* rather than reusing
    # the ones the sweep read minutes ago: the frame-delta band below is only meaningful if the two
    # readings are a known duration apart, and how long the user spent reading the prompt is not.
    # `opened` starts here, at that read, so `elapsed` spans exactly what the frame delta spans.
    opened = time.monotonic()
    if globals_ and manifest.global_scan is not None:
        globals_ = rebase_global_candidates(
            live,
            globals_,
            module=manifest.module,
            module_base=module_base,
            spec=manifest.global_scan,
        )

    # The action window. `confirm_players` drives the sampler, so it consumes the wall-clock time
    # the window is specified to take — which is what makes `elapsed` the duration both oracles are
    # calibrated against. It iterates the generator even with no candidates, so the global oracle
    # still gets its timed window when the player sweep came up empty.
    located = None
    window = _sampling_window(
        live,
        seconds=manifest.action_window_seconds,
        interval=manifest.action_sample_interval,
        progress=progress,
    )
    if players is not None:
        located = confirm_players(
            window,
            players,
            module=manifest.module,
            module_base=module_base,
            manifest=manifest,
            progress=progress,
        )
    else:
        for _ in window:
            pass
    elapsed = time.monotonic() - opened

    # The window has closed. The frame counter has advanced by ~`elapsed` seconds of frames, which
    # is a far sharper test than "it went up": the user's run-2 delta of 96 fits a real counter and
    # run-1's delta of 1 does not, yet the unbanded oracle accepted 22-28 landings on both.
    global_located = None
    if globals_ and manifest.global_scan is not None:
        global_located = confirm_global(
            live,
            globals_,
            module=manifest.module,
            module_base=module_base,
            spec=manifest.global_scan,
            frame_delta=frame_delta_band(manifest.global_scan, elapsed),
            progress=progress,
        )

    before_source: MemorySource = live
    after_source: MemorySource = live
    if located is not None and manifest.base_scan is not None:
        before_frozen = frozen.get(located.match.p1_base)
        if before_frozen is not None:
            before_source = LayeredMemorySource([before_frozen], live)
        # Freeze the *after* struct too. The position scan reads thousands of individual 4-byte
        # floats; against a live handle each lands at a different instant, so a float that merely
        # fluctuates frame-to-frame (an animation weight, a timer) can look like it "moved" and be
        # mistaken for pos_x — and _derive_position takes the first match scanning upward. One bulk
        # read at a single instant makes both snapshots coherent (and ~6000x fewer live reads).
        span = manifest.base_scan.struct_span
        after_base = located.behavior.p1_after_base if located.behavior is not None else None
        if after_base is not None:
            try:
                frozen_after = Region(base=after_base, data=live.read(after_base, span))
                after_source = LayeredMemorySource([frozen_after], live)
            except MemoryReadError:
                # Chain died between snapshots; leave the live source so derive_base_layout reports
                # "chain did not re-resolve" rather than silently scanning stale bytes.
                after_source = live

    table, report = discover_base(
        before_source,
        module=manifest.module,
        module_base=module_base,
        game_version=version,
        manifest=manifest,
        seed=seed,
        seed_version=seed_version,
        source_after=after_source,
        located=located,
        global_located=global_located,
        # Both were swept above, straddling the prompt; None now means "nothing behaved", not
        # "not swept yet". Re-sweeping here would re-read a single instant and prove nothing.
        sweep_global=False,
        sweep_player=False,
        state_map=state_map,
    )
    if table is not None:
        persist(table, report, offsets_dir=offsets_dir)
    return table, report


DERIVE_ACT_PROMPT = (
    "Round start captured.\n"
    "\n"
    "Press Enter, then ALT-TAB BACK TO THE GAME. After a {lead_in:.0f}s countdown the scan\n"
    "watches the heap for ~{window:.0f}s. For all of it, as P1 (Jin), keep acting — on repeat:\n"
    "  walk forward   -> moves pos_x, locating the transform component\n"
    "  jab P2         -> changes move_id (and raises P2's damage_taken if it connects)\n"
    "  jump           -> changes move_id again\n"
    "\n"
    "Nothing has to be timed: the scan accepts a struct whose move_id changed in ANY sample."
)

DERIVE_RESET_PROMPT = (
    "Action window captured.\n"
    "\n"
    "Now force the entity struct to REALLOCATE so the scan can prove its pointer path is durable:\n"
    "reset the round (or briefly change a character and change back), return to the SAME\n"
    "Jin-vs-Kazuya round-start setup, then press Enter. The struct will have moved; a path that\n"
    "still resolves to it is the one worth keeping."
)


def _derive_prompt(manifest: ProbeManifest) -> str:  # pragma: no cover - live-only
    return DERIVE_ACT_PROMPT.format(
        lead_in=manifest.action_lead_in_seconds, window=manifest.action_window_seconds
    )


def _frozen_heap_source(
    live: MemorySource, progress: Progress | None
) -> tuple[MemorySource, list[Region]]:  # pragma: no cover - live-only
    """Freeze every enumerated heap region over the live handle, returning (source, buffers).

    A ``LayeredMemorySource`` serves the frozen heap bytes for reads inside a region and falls back
    to the live handle for the static module (which does not move). This is what gives the scan a
    coherent round-start / post-action / post-reset snapshot from a handle that only reads *now*.
    """
    from tekken_coach.reader.discovery.basescan import LayeredMemorySource  # noqa: PLC0415
    from tekken_coach.reader.discovery.heapscan import _region_buffers  # noqa: PLC0415

    buffers = _region_buffers(live, live.regions(), progress=progress)
    return LayeredMemorySource(buffers, live), buffers


def run_update_offsets_derive(
    process_name: str,
    *,
    offsets_dir: str | Path = DEFAULT_OFFSETS_DIR,
    manifest_path: str | Path = DEFAULT_MANIFEST_PATH,
    version_override: str | None = None,
    act_prompt: Callable[[str], None] | None = None,
    progress: Progress | None = None,
) -> tuple[OffsetTable | None, DiagnosticReport]:  # pragma: no cover - attaches to a live game
    """C4h live re-discovery: derive the whole layout from behavior, no seeded within-struct offset.

    Steps: attach read-only -> detect version -> **freeze the heap at round start** -> prompt the
    user to act (:data:`DERIVE_ACT_PROMPT`), sampling a series of frozen heap snapshots across the
    action window -> prompt for a **round reset** (:data:`DERIVE_RESET_PROMPT`) and freeze the
    reallocated heap -> derive (locate by behavior, reverse-scan for a durable static path, derive
    every field) -> build + write the table. Windows-only, user-run; everything below the attach is
    offline-tested via :func:`discover_derive` against a planted enumerable image with a reallocated
    variant. Reads the heap through the read-only seam and writes a *file*, never the game (§2).
    """
    from tekken_coach.reader.version import detect_running_version  # noqa: PLC0415
    from tekken_coach.reader.win_source import WinMemorySource  # noqa: PLC0415

    prompt = act_prompt if act_prompt is not None else _default_act_prompt
    manifest = load_probe_manifest(manifest_path)
    seed, seed_version = _load_seed(offsets_dir)
    state_map = load_state_map(state_map_path(manifest, manifest_path))

    live: MemorySource = WinMemorySource(process_name)
    version = version_override or detect_running_version(process_name)
    module_base = live.module_base(manifest.module)

    # Round start: freeze the heap (the struct is stable within a round).
    _emit_progress(progress, "  freezing the heap at round start ...")
    before, before_buffers = _frozen_heap_source(live, progress)

    prompt(_derive_prompt(manifest))
    _countdown(manifest.action_lead_in_seconds, progress)

    # The action window: a series of frozen heap snapshots, so a transient move_id that idles back
    # is still caught (the C4g any-sample rule). Sampling freezes each instant coherently.
    during: list[MemorySource] = []
    for _ in _sampling_window(
        live,
        seconds=manifest.action_window_seconds,
        interval=manifest.action_sample_interval,
        progress=progress,
    ):
        snapshot, _buffers = _frozen_heap_source(live, None)
        during.append(snapshot)
    after = during[-1] if during else before

    prompt(DERIVE_RESET_PROMPT)
    _emit_progress(progress, "  freezing the reallocated heap ...")
    realloc, _realloc_buffers = _frozen_heap_source(live, progress)

    inputs = DeriveInputs(
        before=before,
        during=during,
        after=after,
        realloc=realloc,
        heap_buffers=before_buffers,
    )
    table, report = discover_derive(
        inputs,
        module=manifest.module,
        module_base=module_base,
        game_version=version,
        manifest=manifest,
        seed=seed,
        seed_version=seed_version,
        state_map=state_map,
    )
    if table is not None:
        persist(table, report, offsets_dir=offsets_dir)
    return table, report


HOLDER_ACT_PROMPT = (
    "Round start captured; the holder was located by its AoB code signature.\n"
    "\n"
    "Press Enter, then ALT-TAB BACK TO THE GAME. After a {lead_in:.0f}s countdown the scan\n"
    "watches for ~{window:.0f}s. For all of it, as P1 (Jin), keep acting — on repeat:\n"
    "  walk forward   -> moves pos_x, locating the transform component\n"
    "  jab P2         -> changes move_id (and raises P2's damage_taken if it connects)\n"
    "  jump           -> changes move_id again\n"
    "\n"
    "Nothing has to be timed: the scan accepts a move_id that changed in ANY sample."
)


def _holder_prompt(manifest: ProbeManifest) -> str:  # pragma: no cover - live-only
    return HOLDER_ACT_PROMPT.format(
        lead_in=manifest.action_lead_in_seconds, window=manifest.action_window_seconds
    )


def run_update_offsets_holder(
    process_name: str,
    *,
    offsets_dir: str | Path = DEFAULT_OFFSETS_DIR,
    manifest_path: str | Path = DEFAULT_MANIFEST_PATH,
    version_override: str | None = None,
    act_prompt: Callable[[str], None] | None = None,
    progress: Progress | None = None,
    debug_dir: str | Path | None = None,
) -> tuple[OffsetTable | None, DiagnosticReport]:  # pragma: no cover - attaches to a live game
    """C4i live re-discovery: adopt the holder model (AoB code-sig -> holder -> per-player slots).

    Steps: attach read-only -> detect version -> parse the PE -> **find the holder by its AoB code
    signature** and validate it structurally at round start -> sweep the global-struct candidates ->
    freeze both player structs -> prompt the user to act (:data:`HOLDER_ACT_PROMPT`) -> sample a
    timed action window, confirming the acting player's ``move_id`` moved and the global frame
    counter advanced by the window's measured duration -> run the position scan on the frozen
    structs -> build + write the table + register the version. Windows-only, user-run; everything
    below the attach is offline-tested via :func:`discover_holder` against a planted holder world.

    The holder is found **once, before the prompt** (a code signature is a fast, unique identity, so
    there is no candidate sweep), and confirmed **after** it, because the behavioral oracle needs
    the acting player's ``move_id`` across the window and a live handle only reads *now*.
    """
    from tekken_coach.reader.discovery.basescan import (  # noqa: PLC0415
        LayeredMemorySource,
        confirm_global,
        frame_delta_band,
        freeze_struct,
        global_candidates,
        rebase_global_candidates,
    )
    from tekken_coach.reader.discovery.holderscan import find_holder_slot, resolve_holder
    from tekken_coach.reader.discovery.pe import parse_module_image  # noqa: PLC0415
    from tekken_coach.reader.version import detect_running_version  # noqa: PLC0415
    from tekken_coach.reader.win_source import WinMemorySource  # noqa: PLC0415

    prompt = act_prompt if act_prompt is not None else _default_act_prompt
    manifest = load_probe_manifest(manifest_path)
    seed, seed_version = _load_seed(offsets_dir)
    state_map = load_state_map(state_map_path(manifest, manifest_path))
    if manifest.holder_scan is None:
        raise OffsetTableError(
            "no holder_scan spec in the probe manifest; cannot run --holder-scan."
        )

    live: MemorySource = WinMemorySource(process_name)
    version = version_override or detect_running_version(process_name)
    module_base = live.module_base(manifest.module)
    image = parse_module_image(lambda rva, n: live.read(module_base + rva, n))
    if progress is not None:
        progress(
            f"  parsed PE: SizeOfImage {image.size_of_image // 1024} KiB, "
            f"{len(image.sections)} sections"
        )

    # Instant A: locate the holder by its AoB code signature and validate it structurally.
    slot_rva = find_holder_slot(
        live,
        module_base,
        image,
        pattern=manifest.holder_scan.aob_pattern,
        disp32_pos=manifest.holder_scan.disp32_pos,
        progress=progress,
    )
    holder = (
        resolve_holder(live, module_base, slot_rva, manifest.holder_scan, manifest)
        if slot_rva is not None
        else None
    )

    globals_ = []
    if manifest.global_scan is not None:
        globals_ = global_candidates(
            live,
            module=manifest.module,
            module_base=module_base,
            image=image,
            spec=manifest.global_scan,
            progress=progress,
        )

    # Freeze both player structs at round start so the position scan has a coherent *before*.
    # `freeze_struct` shrinks to the largest readable prefix: the manifest struct_span (0x40000) is
    # far larger than the real allocation, so an all-or-nothing full read raises and would drop the
    # whole freeze (the field we need sits in the first few KiB).
    frozen_before: list[Region] = []
    if holder is not None and manifest.base_scan is not None:
        span = manifest.base_scan.struct_span
        for base in holder.player_bases:
            region = freeze_struct(live, base, span)
            if region is not None:
                frozen_before.append(region)
        _emit_progress(
            progress,
            f"  froze {len(frozen_before)} struct(s) at round start "
            f"({', '.join(f'0x{len(r.data):x}B' for r in frozen_before) or 'none'})",
        )

    prompt(_holder_prompt(manifest))
    _countdown(manifest.action_lead_in_seconds, progress)

    opened = time.monotonic()
    if globals_ and manifest.global_scan is not None:
        globals_ = rebase_global_candidates(
            live,
            globals_,
            module=manifest.module,
            module_base=module_base,
            spec=manifest.global_scan,
        )

    # Freeze the player structs at EACH sample instant. `_sampling_window` yields the live handle,
    # but `confirm_holder` reads `during` only after the window closes — by then move_id has idled
    # back, so live references would all read the same post-window value and the behavioral oracle
    # would never see a change (the transient move_id is gone). A per-sample snapshot of the two
    # struct spans captures move_id AT that instant; the holder/slot pointers are stable within a
    # round, so we layer over the live handle for the chain resolution and freeze only the fields.
    # This mirrors `frozen_before`/`frozen_after` above (and the C4h derive path's freeze).
    span = manifest.base_scan.struct_span if manifest.base_scan is not None else 0
    during: list[MemorySource] = []
    debug_samples: list[dict[str, object]] = []
    for _sample in _sampling_window(
        live,
        seconds=manifest.action_window_seconds,
        interval=manifest.action_sample_interval,
        progress=progress,
    ):
        frozen_sample: list[Region] = []
        if holder is not None and span:
            for base in holder.player_bases:
                region = freeze_struct(live, base, span)
                if region is not None:
                    frozen_sample.append(region)
        during.append(LayeredMemorySource(frozen_sample, live) if frozen_sample else live)
        if debug_dir is not None and holder is not None:
            debug_samples.append(_holder_sample_debug(frozen_sample, holder, manifest))
    elapsed = time.monotonic() - opened

    global_located = None
    if globals_ and manifest.global_scan is not None:
        global_located = confirm_global(
            live,
            globals_,
            module=manifest.module,
            module_base=module_base,
            spec=manifest.global_scan,
            frame_delta=frame_delta_band(manifest.global_scan, elapsed),
            progress=progress,
        )

    # Freeze the after struct for the position scan, re-resolving the (possibly reallocated) bases.
    before_source: MemorySource = (
        LayeredMemorySource(frozen_before, live) if frozen_before else live
    )
    after_source: MemorySource = live
    if holder is not None and manifest.base_scan is not None:
        span = manifest.base_scan.struct_span
        from tekken_coach.reader.discovery.holderscan import _resolve_players  # noqa: PLC0415

        after = _resolve_players(live, module_base, holder.slot_rva, manifest.holder_scan)
        if after is not None:
            frozen_after: list[Region] = []
            for base in after[1]:
                region = freeze_struct(live, base, span)
                if region is not None:
                    frozen_after.append(region)
            if frozen_after:
                after_source = LayeredMemorySource(frozen_after, live)

    table, report = discover_holder(
        before_source,
        module=manifest.module,
        module_base=module_base,
        game_version=version,
        manifest=manifest,
        seed=seed,
        seed_version=seed_version,
        source_after=after_source,
        during=during,
        holder=holder,
        slot_rva=slot_rva,
        global_located=global_located,
        sweep_global=False,
        state_map=state_map,
    )
    if debug_dir is not None:
        path = _write_holder_debug(
            debug_dir,
            holder=holder,
            slot_rva=slot_rva,
            manifest=manifest,
            samples=debug_samples,
            elapsed=elapsed,
        )
        _emit_progress(progress, f"  wrote holder-scan debug capture to {path}")
    if table is not None:
        persist(table, report, offsets_dir=offsets_dir)
    return table, report


def _holder_sample_debug(
    frozen: Sequence[Region], holder: HolderMatch, manifest: ProbeManifest
) -> dict[str, object]:  # pragma: no cover - live-only debug capture
    """Decode P1/P2 move_id + damage_taken from one frozen window sample for the debug dump.

    Reads at the *frozen* bases (what the freeze actually captured); a player that failed to freeze
    shows ``frozen: False`` — itself the signal that the full-span read overran the allocation.
    """
    spec = manifest.holder_scan
    assert spec is not None
    by_base = {r.base: r for r in frozen}
    players: list[dict[str, object]] = []
    for base in holder.player_bases:
        region = by_base.get(base)
        if region is None:
            players.append({"base": hex(base), "frozen": False})
            continue
        players.append(
            {
                "base": hex(base),
                "frozen": True,
                "span": hex(len(region.data)),
                "move_id": region.read_scalar(base + spec.move_id_offset, manifest.move_id_kind),
                "damage_taken": region.read_scalar(base + spec.damage_taken_offset, "i32"),
            }
        )
    return {"players": players}


def _write_holder_debug(
    debug_dir: str | Path,
    *,
    holder: HolderMatch | None,
    slot_rva: int | None,
    manifest: ProbeManifest,
    samples: list[dict[str, object]],
    elapsed: float,
) -> Path:  # pragma: no cover - live-only debug capture
    """Dump the round-start landing + per-sample move_id/damage series to a JSON for offline review.

    This live path is untestable in CI, so a structured capture of what each window sample actually
    read (the frozen span achieved, and P1/P2 move_id at every instant) is how a failed behavioral
    oracle gets diagnosed without another live round-trip.
    """
    spec = manifest.holder_scan
    round_start: dict[str, object] | None = None
    if holder is not None:
        round_start = {
            "holder_base": hex(holder.holder_base),
            "player_bases": [hex(b) for b in holder.player_bases],
            "char_ids": list(holder.char_ids),
            "move_ids": list(holder.move_ids),
        }
    out: dict[str, object] = {
        "slot_rva": hex(slot_rva) if slot_rva is not None else None,
        "moving_player": manifest.moving_player,
        "move_id_offset": hex(spec.move_id_offset) if spec is not None else None,
        "damage_taken_offset": hex(spec.damage_taken_offset) if spec is not None else None,
        "struct_span": (
            hex(manifest.base_scan.struct_span) if manifest.base_scan is not None else None
        ),
        "action_window_seconds": manifest.action_window_seconds,
        "action_sample_interval": manifest.action_sample_interval,
        "window_elapsed_seconds": round(elapsed, 3),
        "round_start": round_start,
        "samples": samples,
    }
    directory = Path(debug_dir)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / "holder-scan-debug.json"
    path.write_text(json.dumps(out, indent=2), encoding="utf-8")
    return path


def _emit_progress(progress: Progress | None, message: str) -> None:  # pragma: no cover - live-only
    if progress is not None:
        progress(message)


def _read_snapshots(
    source: MemorySource, manifest: ProbeManifest
) -> tuple[Region, Region]:  # pragma: no cover - live-only
    """Read the player + global scan windows into a ``(player_region, global_region)`` pair."""
    player = snapshot_region(
        source,
        manifest.module,
        manifest.player_window.base_offset,
        manifest.player_window.size,
        absolute=manifest.player_window.absolute,
    )
    global_ = snapshot_region(
        source,
        manifest.module,
        manifest.global_window.base_offset,
        manifest.global_window.size,
        absolute=manifest.global_window.absolute,
    )
    return player, global_


def _countdown(seconds: float, progress: Progress | None) -> None:  # pragma: no cover - live-only
    """Give the user time to alt-tab back to the game before the window opens.

    Without this the window would start while they are still looking at the terminal, and the first
    second or two of samples would show an idle character — harmless for the ``any``-sample oracle,
    wasteful for a window the user is asked to keep moving through.
    """
    remaining = seconds
    while remaining > 0:
        if progress is not None:
            progress(f"  capturing in {math.ceil(remaining)}s ...")
        step = min(1.0, remaining)
        time.sleep(step)
        remaining -= step


def _sampling_window(
    source: MemorySource, *, seconds: float, interval: float, progress: Progress | None
) -> Iterator[MemorySource]:  # pragma: no cover - live-only (offline: a list of planted snapshots)
    """Yield ``source`` on a fixed cadence for ``seconds``, as one "snapshot" per sample.

    The live half of the seam :func:`~.basescan.confirm_players` reads through. Live, every sample
    is the same process handle read at a different instant; offline it is a different planted image
    each time. The oracle cannot tell, which is exactly why the transient-``move_id`` behavior it
    now depends on is testable without a running game. Always yields at least once.
    """
    opened = time.monotonic()
    deadline = opened + seconds
    taken = 0
    while True:
        yield source
        taken += 1
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            break
        time.sleep(min(interval, remaining))
    if progress is not None:
        elapsed = time.monotonic() - opened
        progress(f"  action window closed: {taken} samples over {elapsed:.1f}s")


def _default_act_prompt(message: str) -> None:  # pragma: no cover - interactive, live-only
    input(message)
