"""The ``update-offsets`` orchestration — attach, scan, build, write (docs/02 §4).

Ties the pure pieces together. The split mirrors the rest of the reader:

* :func:`discover` and :func:`persist` are **pure/offline** — given two snapshots (or a built table
  + report), they derive, assemble, and write files. The offline suite drives these against a
  synthetic planted layout, proving the tool's output is consumable by the C4a decoder.
* :func:`run_update_offsets` is the **live orchestration** — it attaches read-only to Tekken 8,
  detects the version, reads the two Jin-vs-Kazuya snapshots (prompting the user to act between
  them), and calls the pure pieces. It needs the running game, so it is ``# pragma: no cover``;
  every step beneath the attach is covered via :func:`discover`/:func:`persist`.

Read-only throughout: it reads process memory through the :class:`MemorySource` seam and writes a
*file* — never the game (docs/02 §2).
"""

from __future__ import annotations

import math
import time
from collections.abc import Callable, Iterator, Sequence
from datetime import UTC, datetime
from pathlib import Path

from tekken_coach.reader.discovery.basescan import (
    GlobalLocated,
    Located,
    Progress,
    derive_base_layout,
)
from tekken_coach.reader.discovery.builder import (
    build_offset_table,
    register_version,
    write_offset_table,
)
from tekken_coach.reader.discovery.derive import DiscoverySnapshots, derive_layout
from tekken_coach.reader.discovery.manifest import (
    DEFAULT_MANIFEST_PATH,
    ProbeManifest,
    load_probe_manifest,
    state_map_path,
)
from tekken_coach.reader.discovery.report import DiagnosticReport, build_report
from tekken_coach.reader.discovery.scanners import Region, snapshot_region
from tekken_coach.reader.faults import MemoryReadError, OffsetTableError
from tekken_coach.reader.memory_source import MemorySource
from tekken_coach.reader.offsets import (
    DEFAULT_OFFSETS_DIR,
    EncodedStateSpec,
    OffsetTable,
    load_offset_index,
    load_state_map,
)

_DEFAULT_NOTES = (
    "Generated by update-offsets (C4c) — clean-room Jin-vs-Kazuya re-discovery. Derived fields are "
    "confident (doctor-validated); other fields carried from the seed table and need calibration."
)

_BASE_SCAN_NOTES = (
    "Generated by update-offsets --base-scan (C4d/C4e/C4f/C4g) — clean-room code-signature "
    "derivation. Derived: player anchor (module base_offset + pointer chain + AOB signature) "
    "confirmed by a BEHAVIORAL oracle (the acting player's move_id changed from its round-start "
    "value in at least one sample of the action window), stride, char_id, move_id, health, "
    "position (transform component), and the global/match anchor + frame_counter/round by the same "
    "temporal "
    "argument, with the frame delta banded to the window's measured duration. Seeded: the encoded "
    "state-word offsets (their VALUE semantics need the docs/02 §8 observation calibration), "
    "match_phase + game_mode (until those are calibrated, capture refuses to record), "
    "heat/rage/input/facing, the state_codes maps."
)


# The single action both behavioral oracles read, and the only thing the user has to get right.
# It is one prompt doing triple duty (docs/02 §4): the walk moves `pos_x` (locating the transform
# component), the jab and the jump each change `move_id` (confirming the struct really is the one
# the player controls), and a *connected* jab raises P2's `damage_taken` (corroboration, not a
# requirement — the jab may whiff).
#
# C4f asked the user to press Enter mid-jump, because it compared `move_id` at exactly two instants.
# That is not a thing a person can do: the jump animation is over long before an alt-tab completes,
# `move_id` is back at its idle value, and the real struct is rejected as frozen (confirmed live —
# the scan found zero behaving candidates). C4g times a window instead and accepts a `move_id` that
# changed in ANY sample, so the user has nothing to time at all: alt-tab, then move.
ACT_PROMPT = (
    "Round start captured.\n"
    "\n"
    "Press Enter, then ALT-TAB BACK TO THE GAME. After a {lead_in:.0f}s countdown the scan\n"
    "watches for ~{window:.0f}s. For all of that time, as P1 (Jin), keep acting — on repeat:\n"
    "  walk forward   -> moves pos_x, locating the transform component\n"
    "  jab P2         -> changes move_id (and raises P2's damage_taken if it connects)\n"
    "  jump           -> changes move_id again, whether or not the jab connected\n"
    "\n"
    "Nothing has to be timed. The scan samples continuously and accepts a struct whose move_id\n"
    "changed in ANY sample, so you only have to be moving while it watches."
)


def _act_prompt(manifest: ProbeManifest) -> str:
    """The action prompt, with the manifest's window durations filled in (they are data)."""
    return ACT_PROMPT.format(
        lead_in=manifest.action_lead_in_seconds, window=manifest.action_window_seconds
    )


# The older C4c value-scan path takes a single before/after pair with no window, so it keeps a
# blocking prompt: it only needs `pos_x` to differ and the frame counter to have advanced, neither
# of which is transient.
WALK_PROMPT = "Round start captured. Now walk P1 (Jin) forward a step, then press Enter."


def _now_iso() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def discover(
    snap: DiscoverySnapshots,
    *,
    module: str,
    module_base: int,
    game_version: str,
    manifest: ProbeManifest,
    seed: OffsetTable,
    seed_version: str,
    discovered_at: str | None = None,
    notes: str = _DEFAULT_NOTES,
) -> tuple[OffsetTable | None, DiagnosticReport]:
    """Derive a layout from two snapshots and assemble a candidate table + diagnostic report (pure).

    Returns ``(table, report)``; ``table`` is ``None`` when the confident core (both anchors + a
    stride) did not resolve — the report then explains what is unresolved so the user can widen the
    manifest and re-run, rather than a broken table being written.
    """
    result = derive_layout(snap, module=module, module_base=module_base, manifest=manifest)
    report = build_report(
        result,
        game_version=game_version,
        module_base=module_base,
        seed=seed,
        seed_version=seed_version,
    )
    table: OffsetTable | None = None
    core_resolved = (
        result.player_anchor is not None
        and result.global_anchor is not None
        and result.stride is not None
    )
    if core_resolved:
        table = build_offset_table(
            result,
            seed,
            game_version=game_version,
            discovered_at=discovered_at or _now_iso(),
            notes=notes,
        )
    return table, report


def discover_base(
    source: MemorySource,
    *,
    module: str,
    module_base: int,
    game_version: str,
    manifest: ProbeManifest,
    seed: OffsetTable,
    seed_version: str,
    source_after: MemorySource | None = None,
    during: Sequence[MemorySource] | None = None,
    located: Located | None = None,
    global_located: GlobalLocated | None = None,
    sweep_global: bool = True,
    sweep_player: bool = True,
    state_map: EncodedStateSpec | None = None,
    progress: Progress | None = None,
    discovered_at: str | None = None,
    notes: str = _BASE_SCAN_NOTES,
) -> tuple[OffsetTable | None, DiagnosticReport]:
    """C4d/C4e: derive both anchors via the code-signature scans, assemble a candidate table (pure).

    Mirrors :func:`discover` but for the code-signature path: it reads through the ``MemorySource``
    seam (following pointer chains), so it takes ``source``(s) rather than pre-captured windows.
    ``source_after`` (a snapshot at the end of the user's action) enables the position derivation
    and the behavioral confirmation of both anchors; without it the player landing is accepted on a
    single instant and flagged as unconfirmed. ``during`` is the whole action window the behavioral
    oracle folds over — a candidate's ``move_id`` only has to differ in *one* of those samples,
    which is what makes the oracle satisfiable by a person (C4g); it defaults to the single-sample
    ``[source_after]``. ``located`` / ``global_located`` reuse sweeps the caller already ran, and
    ``sweep_player`` / ``sweep_global`` say whether a missing one means "found nothing" (the live
    path, which must sweep before the user acts) or "not swept yet". ``progress`` logs the sweeps.
    ``state_map`` is the encoded-state value -> meaning data written into the table. Returns
    ``(table, report)``; ``table`` is ``None`` when the player anchor or a constant stride did not
    resolve (e.g. the two-level P2 case) — the report then explains what to do.
    """
    result = derive_base_layout(
        source,
        module=module,
        module_base=module_base,
        manifest=manifest,
        seed=seed,
        source_after=source_after,
        during=during,
        located=located,
        global_located=global_located,
        sweep_global=sweep_global,
        sweep_player=sweep_player,
        state_map=state_map,
        progress=progress,
    )
    report = build_report(
        result,
        game_version=game_version,
        module_base=module_base,
        seed=seed,
        seed_version=seed_version,
    )
    table: OffsetTable | None = None
    core_resolved = (
        result.player_anchor is not None
        and result.global_anchor is not None
        and result.stride is not None
    )
    if core_resolved:
        table = build_offset_table(
            result,
            seed,
            game_version=game_version,
            discovered_at=discovered_at or _now_iso(),
            notes=notes,
        )
    return table, report


def persist(
    table: OffsetTable, report: DiagnosticReport, *, offsets_dir: str | Path = DEFAULT_OFFSETS_DIR
) -> DiagnosticReport:
    """Write ``table`` to ``<offsets_dir>/<version>.json`` and register it; annotate the report.

    Fail-closed behavior elsewhere is untouched: this only *adds* a version binding (additive), so
    an unknown *other* version still fails closed at select time (docs/02 §3).
    """
    path = write_offset_table(offsets_dir, table)
    register_version(offsets_dir, table.game_version, file_name=path.name)
    report.table_written = str(path)
    report.index_written = str(Path(offsets_dir) / "index.json")
    return report


def _load_seed(offsets_dir: str | Path) -> tuple[OffsetTable, str]:
    """Load the seed table (the index's detected/known-good build) for carrying non-derived fields.

    Raises :class:`OffsetTableError` if no baseline exists — update-offsets refines a prior table
    rather than inventing one from nothing; bring-up ships the C4a placeholder as that baseline.
    """
    from tekken_coach.reader.offsets import select_offset_table  # noqa: PLC0415

    index = load_offset_index(offsets_dir)
    seed_version = index.detected_version
    try:
        seed = select_offset_table(seed_version, offsets_dir)
    except OffsetTableError as exc:
        raise OffsetTableError(
            f"no seed offset table for the index's detected_version {seed_version!r}; "
            "update-offsets carries non-derived fields from a prior table — keep the checked-in "
            "baseline (the C4a placeholder) in place. Original error: " + str(exc)
        ) from exc
    return seed, seed_version


def run_update_offsets(
    process_name: str,
    *,
    offsets_dir: str | Path = DEFAULT_OFFSETS_DIR,
    manifest_path: str | Path = DEFAULT_MANIFEST_PATH,
    version_override: str | None = None,
    act_prompt: Callable[[str], None] | None = None,
) -> tuple[OffsetTable | None, DiagnosticReport]:  # pragma: no cover - attaches to a live game
    """Full live re-discovery: attach read-only, scan the Jin-vs-Kazuya setup, write the table.

    Steps: attach (read-only) -> detect version -> read snapshot A at round start -> prompt the user
    to walk P1 and press a button -> read snapshot B -> derive -> build + write the candidate table
    and register the version -> return ``(table, report)``. Windows-only, user-run. Everything below
    the attach/read is offline-tested via :func:`discover`/:func:`persist`.
    """
    from tekken_coach.reader.version import detect_running_version  # noqa: PLC0415
    from tekken_coach.reader.win_source import WinMemorySource  # noqa: PLC0415

    prompt = act_prompt if act_prompt is not None else _default_act_prompt
    manifest = load_probe_manifest(manifest_path)
    seed, seed_version = _load_seed(offsets_dir)

    source: MemorySource = WinMemorySource(process_name)
    version = version_override or detect_running_version(process_name)
    module_base = source.module_base(manifest.module)

    snap_before = _read_snapshots(source, manifest)
    prompt(WALK_PROMPT)
    snap_after = _read_snapshots(source, manifest)
    snap = DiscoverySnapshots(
        player_before=snap_before[0],
        player_after=snap_after[0],
        global_before=snap_before[1],
        global_after=snap_after[1],
    )

    table, report = discover(
        snap,
        module=manifest.module,
        module_base=module_base,
        game_version=version,
        manifest=manifest,
        seed=seed,
        seed_version=seed_version,
    )
    if table is not None:
        persist(table, report, offsets_dir=offsets_dir)
    return table, report


def run_update_offsets_base(
    process_name: str,
    *,
    offsets_dir: str | Path = DEFAULT_OFFSETS_DIR,
    manifest_path: str | Path = DEFAULT_MANIFEST_PATH,
    version_override: str | None = None,
    act_prompt: Callable[[str], None] | None = None,
    progress: Progress | None = None,
) -> tuple[OffsetTable | None, DiagnosticReport]:  # pragma: no cover - attaches to a live game
    """C4d/C4e/C4g live re-discovery: attach read-only, code-sig-scan both structs, write the table.

    Steps: attach (read-only) -> detect version -> code-signature sweep for the player-struct and
    global-struct *candidates* at round start -> prompt the user to act (:data:`ACT_PROMPT`) -> let
    them alt-tab back -> **sample a timed action window**, folding each candidate's ``move_id`` over
    every sample -> confirm the global struct against the window's measured duration -> run the
    position scan -> derive -> build + write the candidate table + register the version.
    Windows-only, user-run. The scans follow pointer chains through the live ``MemorySource``;
    everything below the attach is offline-tested via :func:`discover_base` against a planted flat
    image, and the window itself via a planted *series* of images.

    Both sweeps run **once, here**, before the prompt, and their results are confirmed after it —
    not as an optimization but because **both oracles are behavioral**. The global oracle needs the
    frame counter at two instants a known duration apart; the player oracle needs the acting
    player's ``move_id`` across a window, because a struct that merely reads plausibly at round
    start is not necessarily the one the player is controlling (it was not, live, on 5.02.01) *and*
    because ``move_id`` is transient — a jab lasts half a second, so the moment the user's finger
    reaches Enter it has already gone back to idle (C4g). A live handle only ever reads *now*, so
    sampling across the user's action is the only way to observe either signal. ``progress`` (from
    the command layer) makes the sweeps and the window observable.
    """
    from tekken_coach.reader.discovery.basescan import (  # noqa: PLC0415
        LayeredMemorySource,
        confirm_global,
        confirm_players,
        frame_delta_band,
        global_candidates,
        player_candidates,
        rebase_global_candidates,
    )
    from tekken_coach.reader.discovery.pe import parse_module_image  # noqa: PLC0415
    from tekken_coach.reader.version import detect_running_version  # noqa: PLC0415
    from tekken_coach.reader.win_source import WinMemorySource  # noqa: PLC0415

    prompt = act_prompt if act_prompt is not None else _default_act_prompt
    manifest = load_probe_manifest(manifest_path)
    seed, seed_version = _load_seed(offsets_dir)
    state_map = load_state_map(state_map_path(manifest, manifest_path))

    live: MemorySource = WinMemorySource(process_name)
    version = version_override or detect_running_version(process_name)
    module_base = live.module_base(manifest.module)
    # Parsed once and handed to both sweeps (they bound themselves to the same data sections). Each
    # sweep only announces a PE parse it performed itself, so announce this one here.
    image = parse_module_image(lambda rva, n: live.read(module_base + rva, n))
    if progress is not None:
        progress(
            f"  parsed PE: SizeOfImage {image.size_of_image // 1024} KiB, "
            f"{len(image.sections)} sections"
        )

    # Instant A. Both sweeps produce *candidates*, not answers.
    players = player_candidates(
        live,
        module=manifest.module,
        module_base=module_base,
        manifest=manifest,
        image=image,
        progress=progress,
    )
    globals_ = []
    if manifest.global_scan is not None:
        globals_ = global_candidates(
            live,
            module=manifest.module,
            module_base=module_base,
            image=image,
            spec=manifest.global_scan,
            progress=progress,
        )

    # Freeze every candidate struct at round start so the position scan has a genuine *before*
    # snapshot whichever candidate the action confirms: a single live handle only reads the current
    # instant. The static chain re-resolves either way — that is exactly why C4d anchors in code.
    frozen: dict[int, Region] = {}
    if players is not None and manifest.base_scan is not None:
        span = manifest.base_scan.struct_span
        for match in players.strong:
            if match.p1_base in frozen:
                continue
            try:
                frozen[match.p1_base] = Region(
                    base=match.p1_base, data=live.read(match.p1_base, span)
                )
            except MemoryReadError:
                continue

    prompt(_act_prompt(manifest))
    _countdown(manifest.action_lead_in_seconds, progress)

    # The window opens. Re-read the global candidates' round-start values *now* rather than reusing
    # the ones the sweep read minutes ago: the frame-delta band below is only meaningful if the two
    # readings are a known duration apart, and how long the user spent reading the prompt is not.
    # `opened` starts here, at that read, so `elapsed` spans exactly what the frame delta spans.
    opened = time.monotonic()
    if globals_ and manifest.global_scan is not None:
        globals_ = rebase_global_candidates(
            live,
            globals_,
            module=manifest.module,
            module_base=module_base,
            spec=manifest.global_scan,
        )

    # The action window. `confirm_players` drives the sampler, so it consumes the wall-clock time
    # the window is specified to take — which is what makes `elapsed` the duration both oracles are
    # calibrated against. It iterates the generator even with no candidates, so the global oracle
    # still gets its timed window when the player sweep came up empty.
    located = None
    window = _sampling_window(
        live,
        seconds=manifest.action_window_seconds,
        interval=manifest.action_sample_interval,
        progress=progress,
    )
    if players is not None:
        located = confirm_players(
            window,
            players,
            module=manifest.module,
            module_base=module_base,
            manifest=manifest,
            progress=progress,
        )
    else:
        for _ in window:
            pass
    elapsed = time.monotonic() - opened

    # The window has closed. The frame counter has advanced by ~`elapsed` seconds of frames, which
    # is a far sharper test than "it went up": the user's run-2 delta of 96 fits a real counter and
    # run-1's delta of 1 does not, yet the unbanded oracle accepted 22-28 landings on both.
    global_located = None
    if globals_ and manifest.global_scan is not None:
        global_located = confirm_global(
            live,
            globals_,
            module=manifest.module,
            module_base=module_base,
            spec=manifest.global_scan,
            frame_delta=frame_delta_band(manifest.global_scan, elapsed),
            progress=progress,
        )

    before_source: MemorySource = live
    after_source: MemorySource = live
    if located is not None and manifest.base_scan is not None:
        before_frozen = frozen.get(located.match.p1_base)
        if before_frozen is not None:
            before_source = LayeredMemorySource([before_frozen], live)
        # Freeze the *after* struct too. The position scan reads thousands of individual 4-byte
        # floats; against a live handle each lands at a different instant, so a float that merely
        # fluctuates frame-to-frame (an animation weight, a timer) can look like it "moved" and be
        # mistaken for pos_x — and _derive_position takes the first match scanning upward. One bulk
        # read at a single instant makes both snapshots coherent (and ~6000x fewer live reads).
        span = manifest.base_scan.struct_span
        after_base = located.behavior.p1_after_base if located.behavior is not None else None
        if after_base is not None:
            try:
                frozen_after = Region(base=after_base, data=live.read(after_base, span))
                after_source = LayeredMemorySource([frozen_after], live)
            except MemoryReadError:
                # Chain died between snapshots; leave the live source so derive_base_layout reports
                # "chain did not re-resolve" rather than silently scanning stale bytes.
                after_source = live

    table, report = discover_base(
        before_source,
        module=manifest.module,
        module_base=module_base,
        game_version=version,
        manifest=manifest,
        seed=seed,
        seed_version=seed_version,
        source_after=after_source,
        located=located,
        global_located=global_located,
        # Both were swept above, straddling the prompt; None now means "nothing behaved", not
        # "not swept yet". Re-sweeping here would re-read a single instant and prove nothing.
        sweep_global=False,
        sweep_player=False,
        state_map=state_map,
    )
    if table is not None:
        persist(table, report, offsets_dir=offsets_dir)
    return table, report


def _read_snapshots(
    source: MemorySource, manifest: ProbeManifest
) -> tuple[Region, Region]:  # pragma: no cover - live-only
    """Read the player + global scan windows into a ``(player_region, global_region)`` pair."""
    player = snapshot_region(
        source,
        manifest.module,
        manifest.player_window.base_offset,
        manifest.player_window.size,
        absolute=manifest.player_window.absolute,
    )
    global_ = snapshot_region(
        source,
        manifest.module,
        manifest.global_window.base_offset,
        manifest.global_window.size,
        absolute=manifest.global_window.absolute,
    )
    return player, global_


def _countdown(seconds: float, progress: Progress | None) -> None:  # pragma: no cover - live-only
    """Give the user time to alt-tab back to the game before the window opens.

    Without this the window would start while they are still looking at the terminal, and the first
    second or two of samples would show an idle character — harmless for the ``any``-sample oracle,
    wasteful for a window the user is asked to keep moving through.
    """
    remaining = seconds
    while remaining > 0:
        if progress is not None:
            progress(f"  capturing in {math.ceil(remaining)}s ...")
        step = min(1.0, remaining)
        time.sleep(step)
        remaining -= step


def _sampling_window(
    source: MemorySource, *, seconds: float, interval: float, progress: Progress | None
) -> Iterator[MemorySource]:  # pragma: no cover - live-only (offline: a list of planted snapshots)
    """Yield ``source`` on a fixed cadence for ``seconds``, as one "snapshot" per sample.

    The live half of the seam :func:`~.basescan.confirm_players` reads through. Live, every sample
    is the same process handle read at a different instant; offline it is a different planted image
    each time. The oracle cannot tell, which is exactly why the transient-``move_id`` behavior it
    now depends on is testable without a running game. Always yields at least once.
    """
    opened = time.monotonic()
    deadline = opened + seconds
    taken = 0
    while True:
        yield source
        taken += 1
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            break
        time.sleep(min(interval, remaining))
    if progress is not None:
        elapsed = time.monotonic() - opened
        progress(f"  action window closed: {taken} samples over {elapsed:.1f}s")


def _default_act_prompt(message: str) -> None:  # pragma: no cover - interactive, live-only
    input(message)
