"""The ``update-offsets`` orchestration — attach, scan, build, write (docs/02 §4).

Ties the pure pieces together. The split mirrors the rest of the reader:

* :func:`discover` and :func:`persist` are **pure/offline** — given two snapshots (or a built table
  + report), they derive, assemble, and write files. The offline suite drives these against a
  synthetic planted layout, proving the tool's output is consumable by the C4a decoder.
* :func:`run_update_offsets` is the **live orchestration** — it attaches read-only to Tekken 8,
  detects the version, reads the two Jin-vs-Kazuya snapshots (prompting the user to act between
  them), and calls the pure pieces. It needs the running game, so it is ``# pragma: no cover``;
  every step beneath the attach is covered via :func:`discover`/:func:`persist`.

Read-only throughout: it reads process memory through the :class:`MemorySource` seam and writes a
*file* — never the game (docs/02 §2).
"""

from __future__ import annotations

from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path

from tekken_coach.reader.discovery.basescan import derive_base_layout
from tekken_coach.reader.discovery.builder import (
    build_offset_table,
    register_version,
    write_offset_table,
)
from tekken_coach.reader.discovery.derive import DiscoverySnapshots, derive_layout
from tekken_coach.reader.discovery.manifest import (
    DEFAULT_MANIFEST_PATH,
    ProbeManifest,
    load_probe_manifest,
)
from tekken_coach.reader.discovery.report import DiagnosticReport, build_report
from tekken_coach.reader.discovery.scanners import Region, snapshot_region
from tekken_coach.reader.faults import OffsetTableError
from tekken_coach.reader.memory_source import MemorySource
from tekken_coach.reader.offsets import DEFAULT_OFFSETS_DIR, OffsetTable, load_offset_index

_DEFAULT_NOTES = (
    "Generated by update-offsets (C4c) — clean-room Jin-vs-Kazuya re-discovery. Derived fields are "
    "confident (doctor-validated); other fields carried from the seed table and need calibration."
)

_BASE_SCAN_NOTES = (
    "Generated by update-offsets --base-scan (C4d) — clean-room code-signature base derivation. "
    "player anchor (module base_offset + pointer chain + AOB signature) and char_id/move_id/health/"
    "position are derived; global anchor and other fields carried from the seed table and need "
    "calibration."
)


def _now_iso() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def discover(
    snap: DiscoverySnapshots,
    *,
    module: str,
    module_base: int,
    game_version: str,
    manifest: ProbeManifest,
    seed: OffsetTable,
    seed_version: str,
    discovered_at: str | None = None,
    notes: str = _DEFAULT_NOTES,
) -> tuple[OffsetTable | None, DiagnosticReport]:
    """Derive a layout from two snapshots and assemble a candidate table + diagnostic report (pure).

    Returns ``(table, report)``; ``table`` is ``None`` when the confident core (both anchors + a
    stride) did not resolve — the report then explains what is unresolved so the user can widen the
    manifest and re-run, rather than a broken table being written.
    """
    result = derive_layout(snap, module=module, module_base=module_base, manifest=manifest)
    report = build_report(
        result,
        game_version=game_version,
        module_base=module_base,
        seed=seed,
        seed_version=seed_version,
    )
    table: OffsetTable | None = None
    core_resolved = (
        result.player_anchor is not None
        and result.global_anchor is not None
        and result.stride is not None
    )
    if core_resolved:
        table = build_offset_table(
            result,
            seed,
            game_version=game_version,
            discovered_at=discovered_at or _now_iso(),
            notes=notes,
        )
    return table, report


def discover_base(
    source: MemorySource,
    *,
    module: str,
    module_base: int,
    game_version: str,
    manifest: ProbeManifest,
    seed: OffsetTable,
    seed_version: str,
    source_after: MemorySource | None = None,
    discovered_at: str | None = None,
    notes: str = _BASE_SCAN_NOTES,
) -> tuple[OffsetTable | None, DiagnosticReport]:
    """C4d: derive the player anchor via the code-signature scan, assemble a candidate table (pure).

    Mirrors :func:`discover` but for the code-signature path: it reads through the ``MemorySource``
    seam (following pointer chains), so it takes ``source``(s) rather than pre-captured windows.
    ``source_after`` (a second snapshot after the user walks + presses a button) enables the
    position scan; without it position is seeded. Returns ``(table, report)``; ``table`` is ``None``
    when the player anchor or a constant stride did not resolve (e.g. the two-level P2 case) — the
    report then explains what to do.
    """
    result = derive_base_layout(
        source,
        module=module,
        module_base=module_base,
        manifest=manifest,
        seed=seed,
        source_after=source_after,
    )
    report = build_report(
        result,
        game_version=game_version,
        module_base=module_base,
        seed=seed,
        seed_version=seed_version,
    )
    table: OffsetTable | None = None
    core_resolved = (
        result.player_anchor is not None
        and result.global_anchor is not None
        and result.stride is not None
    )
    if core_resolved:
        table = build_offset_table(
            result,
            seed,
            game_version=game_version,
            discovered_at=discovered_at or _now_iso(),
            notes=notes,
        )
    return table, report


def persist(
    table: OffsetTable, report: DiagnosticReport, *, offsets_dir: str | Path = DEFAULT_OFFSETS_DIR
) -> DiagnosticReport:
    """Write ``table`` to ``<offsets_dir>/<version>.json`` and register it; annotate the report.

    Fail-closed behavior elsewhere is untouched: this only *adds* a version binding (additive), so
    an unknown *other* version still fails closed at select time (docs/02 §3).
    """
    path = write_offset_table(offsets_dir, table)
    register_version(offsets_dir, table.game_version, file_name=path.name)
    report.table_written = str(path)
    report.index_written = str(Path(offsets_dir) / "index.json")
    return report


def _load_seed(offsets_dir: str | Path) -> tuple[OffsetTable, str]:
    """Load the seed table (the index's detected/known-good build) for carrying non-derived fields.

    Raises :class:`OffsetTableError` if no baseline exists — update-offsets refines a prior table
    rather than inventing one from nothing; bring-up ships the C4a placeholder as that baseline.
    """
    from tekken_coach.reader.offsets import select_offset_table  # noqa: PLC0415

    index = load_offset_index(offsets_dir)
    seed_version = index.detected_version
    try:
        seed = select_offset_table(seed_version, offsets_dir)
    except OffsetTableError as exc:
        raise OffsetTableError(
            f"no seed offset table for the index's detected_version {seed_version!r}; "
            "update-offsets carries non-derived fields from a prior table — keep the checked-in "
            "baseline (the C4a placeholder) in place. Original error: " + str(exc)
        ) from exc
    return seed, seed_version


def run_update_offsets(
    process_name: str,
    *,
    offsets_dir: str | Path = DEFAULT_OFFSETS_DIR,
    manifest_path: str | Path = DEFAULT_MANIFEST_PATH,
    version_override: str | None = None,
    act_prompt: Callable[[str], None] | None = None,
) -> tuple[OffsetTable | None, DiagnosticReport]:  # pragma: no cover - attaches to a live game
    """Full live re-discovery: attach read-only, scan the Jin-vs-Kazuya setup, write the table.

    Steps: attach (read-only) -> detect version -> read snapshot A at round start -> prompt the user
    to walk P1 and press a button -> read snapshot B -> derive -> build + write the candidate table
    and register the version -> return ``(table, report)``. Windows-only, user-run. Everything below
    the attach/read is offline-tested via :func:`discover`/:func:`persist`.
    """
    from tekken_coach.reader.version import detect_running_version  # noqa: PLC0415
    from tekken_coach.reader.win_source import WinMemorySource  # noqa: PLC0415

    prompt = act_prompt if act_prompt is not None else _default_act_prompt
    manifest = load_probe_manifest(manifest_path)
    seed, seed_version = _load_seed(offsets_dir)

    source: MemorySource = WinMemorySource(process_name)
    version = version_override or detect_running_version(process_name)
    module_base = source.module_base(manifest.module)

    snap_before = _read_snapshots(source, manifest)
    prompt(
        "Round start captured. Now walk P1 (Jin) forward a step and press a button, then press "
        "Enter to capture the second snapshot..."
    )
    snap_after = _read_snapshots(source, manifest)
    snap = DiscoverySnapshots(
        player_before=snap_before[0],
        player_after=snap_after[0],
        global_before=snap_before[1],
        global_after=snap_after[1],
    )

    table, report = discover(
        snap,
        module=manifest.module,
        module_base=module_base,
        game_version=version,
        manifest=manifest,
        seed=seed,
        seed_version=seed_version,
    )
    if table is not None:
        persist(table, report, offsets_dir=offsets_dir)
    return table, report


def run_update_offsets_base(
    process_name: str,
    *,
    offsets_dir: str | Path = DEFAULT_OFFSETS_DIR,
    manifest_path: str | Path = DEFAULT_MANIFEST_PATH,
    version_override: str | None = None,
    act_prompt: Callable[[str], None] | None = None,
) -> tuple[OffsetTable | None, DiagnosticReport]:  # pragma: no cover - attaches to a live game
    """C4d live re-discovery: attach read-only, code-sig-scan the player struct, write the table.

    Steps: attach (read-only) -> detect version -> code-signature scan for the player-struct pointer
    at round start -> prompt the user to walk P1 and press a button -> re-read for the position scan
    -> derive -> build + write the candidate table + register the version. Windows-only, user-run.
    The scan follows pointer chains through the live ``MemorySource``; everything below the attach
    is offline-tested via :func:`discover_base` against a planted flat image.
    """
    from tekken_coach.reader.discovery.basescan import (  # noqa: PLC0415
        LayeredMemorySource,
        locate_player_struct,
    )
    from tekken_coach.reader.version import detect_running_version  # noqa: PLC0415
    from tekken_coach.reader.win_source import WinMemorySource  # noqa: PLC0415

    prompt = act_prompt if act_prompt is not None else _default_act_prompt
    manifest = load_probe_manifest(manifest_path)
    seed, seed_version = _load_seed(offsets_dir)

    live: MemorySource = WinMemorySource(process_name)
    version = version_override or detect_running_version(process_name)
    module_base = live.module_base(manifest.module)

    # Freeze the located struct at round start so the position scan has a genuine *before* snapshot:
    # a single live handle only reads the current instant, so we capture the struct bytes now, let
    # the user act, then read the moved struct live. The static chain re-resolves either way — that
    # is exactly why C4d anchors in code, not the heap.
    before_source: MemorySource = live
    located = locate_player_struct(
        live,
        module=manifest.module,
        module_base=module_base,
        manifest=manifest,
        hint=seed.players.anchor.signature,
    )
    if located is not None and manifest.base_scan is not None:
        span = manifest.base_scan.struct_span
        frozen = Region(base=located.match.p1_base, data=live.read(located.match.p1_base, span))
        before_source = LayeredMemorySource([frozen], live)
        prompt(
            "Struct located at round start. Now walk P1 (Jin) forward a step and press a button, "
            "then press Enter to capture the second snapshot for the position scan..."
        )

    table, report = discover_base(
        before_source,
        module=manifest.module,
        module_base=module_base,
        game_version=version,
        manifest=manifest,
        seed=seed,
        seed_version=seed_version,
        source_after=live,
    )
    if table is not None:
        persist(table, report, offsets_dir=offsets_dir)
    return table, report


def _read_snapshots(
    source: MemorySource, manifest: ProbeManifest
) -> tuple[Region, Region]:  # pragma: no cover - live-only
    """Read the player + global scan windows into a ``(player_region, global_region)`` pair."""
    player = snapshot_region(
        source,
        manifest.module,
        manifest.player_window.base_offset,
        manifest.player_window.size,
        absolute=manifest.player_window.absolute,
    )
    global_ = snapshot_region(
        source,
        manifest.module,
        manifest.global_window.base_offset,
        manifest.global_window.size,
        absolute=manifest.global_window.absolute,
    )
    return player, global_


def _default_act_prompt(message: str) -> None:  # pragma: no cover - interactive, live-only
    input(message)
